### PR TITLE
Created DeepObjectAssert JA action

### PR DESCRIPTION
**Pull request by kimpellikaan**
More often then not when testing we want to compare complete objects. Until now this has not been possible so I created a class which does just that.

This action receives 2 objects and returns true when the attributes are the same. It log's the differences and handels edge cases like removing default fields, null values and empty lists.

I did encounter one problem, I was unable to put my test in a package /communitycommons/tests without the compiler failing. If someone can help me fix this that would be awesome.

### CODE REVIEW

**Comment by RoelandSalij** [comment]
Thanks for the pull request!
We're investigating if we can split up this module into several smaller modules as this module is becoming a snowball rolling of a snowy hill.
As a result merging will be done after this drill.

**Comment by kimpellikaan** [comment]
@RoelandSalij Can I help? If you can do me one favour, have a test folder for the unit tests in the new setup.

**Comment by RoelandSalij** [comment]
Hi,
Yes if you would like to share your opinion view on how we can take this thing forward, I would very much appreciate that. :)
Unfortunately, merging is more cumbersomoe in github which makes it difficult to work on Mendix projects together extensively in combination with GitHub.

**Comment by kimpellikaan** [comment]
Yea, I figured that....

Does mxgit still work or do you overwrite the pr every time?

**Comment by reinouts** [comment]
old

**Pull request closed without merging**
